# Generated by Django 2.1.4 on 2018-12-05 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vizualisations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vizualisation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='edge',
            name='vizualisation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='vizualisations.Vizualisation'),
            preserve_default=False,
        ),
    ]
