# Generated by Django 2.1.4 on 2018-12-06 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vizualisations', '0002_auto_20181205_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='ip',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
